### ISSUE TITLE
Add @nwillems as someone who can manage ticket in the project

### ISSUE THREAD

**Issue by nwillems** [klyrr/ts-reading-list#1]
Can I has access please? I would like to add some elements to the reading list:

- [object-oriented-vs-functional-programming.pdf](https://github.com/klyrr/ts-reading-list/files/1646391/object-oriented-vs-functional-programming.pdf)
- [webarch_icse2000.pdf](https://github.com/klyrr/ts-reading-list/files/1646394/webarch_icse2000.pdf)
- [reflections_on_rest.pdf](https://github.com/klyrr/ts-reading-list/files/1646395/reflections_on_rest.pdf)
- [Naur.pdf](https://github.com/klyrr/ts-reading-list/files/1646402/Naur.pdf)

The two ones on REST aren't super interesting, but the view on the internet that they present is rather interesting.

**Comment by klyrr** [comment]
You can haz access.

**Comment by nwillems** [comment]
I haz teh axeszZz
